import type { Product } from './types';

export const products: Product[] = [
  {
    id: '1',
    slug: 'victorian-dream-lolita-dress',
    name: 'Victorian Dream Lolita Dress',
    description: 'A stunning Gothic Lolita dress with intricate lace details, a velvet bodice, and a full, flowing skirt. Perfect for elegant tea parties and moonlit strolls.',
    price: 18500,
    images: ['https://placehold.co/600x800.png', 'https://placehold.co/600x800.png', 'https://placehold.co/600x800.png'],
    category: 'Gothic Lolita',
    colors: ['Black', 'Burgundy'],
    sizes: ['S', 'M', 'L'],
    inStock: true,
    styleTags: ['Gothic Lolita', 'Victorian', 'Elegant', 'Lace'],
    isFeatured: true,
  },
  {
    id: '2',
    slug: 'strawberry-shortcake-jumper-skirt',
    name: 'Strawberry Shortcake Jumper Skirt',
    description: 'The sweetest jumper skirt in pastel pink, adorned with strawberry prints, ruffles, and a large satin bow. A must-have for any Sweet Lolita wardrobe.',
    price: 12000,
    images: ['https://placehold.co/600x800.png', 'https://placehold.co/600x800.png', 'https://placehold.co/600x800.png'],
    category: 'Sweet Lolita',
    colors: ['Pink', 'White'],
    sizes: ['S', 'M'],
    inStock: true,
    styleTags: ['Sweet Lolita', 'Kawaii', 'Pastel', 'Strawberry'],
    isFeatured: true,
  },
  {
    id: '3',
    slug: 'leopard-print-gyaru-set',
    name: 'Leopard Print Gyaru Set',
    description: 'Unleash your inner goddess with this bold leopard print top and mini-skirt set. Features gold chain details and a flattering fit, perfect for hitting the town.',
    price: 9500,
    images: ['https://placehold.co/600x800.png', 'https://placehold.co/600x800.png'],
    category: 'Gyaru',
    colors: ['Leopard', 'Gold'],
    sizes: ['S', 'M', 'L'],
    inStock: true,
    styleTags: ['Gyaru', 'Bold', 'Leopard Print', 'Party'],
    isFeatured: true,
  },
  {
    id: '4',
    slug: 'sakura-romance-shoujo-blouse',
    name: 'Sakura Romance Shoujo Blouse',
    description: 'A dreamy, soft blouse with sailor-style collar, cherry blossom embroidery, and delicate ribbon ties. It captures the pure essence of shoujo manga romance.',
    price: 7800,
    images: ['https://placehold.co/600x800.png'],
    category: 'Shoujo',
    colors: ['White', 'Pink'],
    sizes: ['One Size'],
    inStock: true,
    styleTags: ['Shoujo', 'Sailor Collar', 'Embroidery', 'Romantic'],
    isFeatured: true,
  },
    {
    id: '5',
    slug: 'midnight-rose-corset-skirt',
    name: 'Midnight Rose Corset Skirt',
    description: 'An elegant high-waisted skirt featuring a corset lacing front, dark rose patterns, and layers of black tulle. A signature piece for any Gothic Lolita.',
    price: 11000,
    images: ['https://placehold.co/600x800.png', 'https://placehold.co/600x800.png'],
    category: 'Gothic Lolita',
    colors: ['Black', 'Red'],
    sizes: ['S', 'M', 'L', 'XL'],
    inStock: true,
    styleTags: ['Gothic Lolita', 'Corset', 'Rose', 'Tulle'],
  },
  {
    id: '6',
    slug: 'candy-carousel-op',
    name: 'Candy Carousel One-Piece',
    description: 'A whimsical one-piece dress with a pastel carousel horse print, frilly sleeves, and a sweet peter pan collar. Perfect for a day at the amusement park.',
    price: 14500,
    images: ['https://placehold.co/600x800.png', 'https://placehold.co/600x800.png'],
    category: 'Sweet Lolita',
    colors: ['Lavender', 'Mint', 'Pink'],
    sizes: ['M', 'L'],
    inStock: false,
    styleTags: ['Sweet Lolita', 'Pastel', 'Carousel', 'Whimsical'],
  },
  {
    id: '7',
    slug: 'shibuya-gal-denim-shorts',
    name: 'Shibuya Gal Denim Shorts',
    description: 'Distressed denim shorts with flashy rhinestone details and a fluffy faux fur trim. The ultimate statement piece for a bold Gyaru look.',
    price: 8200,
    images: ['https://placehold.co/600x800.png'],
    category: 'Gyaru',
    colors: ['Blue Denim'],
    sizes: ['S', 'M'],
    inStock: true,
    styleTags: ['Gyaru', 'Denim', 'Rhinestone', 'Shibuya'],
  },
  {
    id: '8',
    slug: 'star-guardian-pleated-skirt',
    name: 'Star Guardian Pleated Skirt',
    description: 'A magical girl-inspired pleated skirt in a celestial star print with a cute bow accent. Channel your inner guardian of love and justice!',
    price: 6500,
    images: ['https://placehold.co/600x800.png', 'https://placehold.co/600x800.png'],
    category: 'Shoujo',
    colors: ['Navy', 'Pastel Blue'],
    sizes: ['S', 'M', 'L'],
    inStock: true,
    styleTags: ['Shoujo', 'Magical Girl', 'Stars', 'Pleated Skirt'],
  },
];
